//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 證件號碼格式不符合 的本地化字符串。
        /// </summary>
        public static string _Code11001_1 {
            get {
                return ResourceManager.GetString("_Code11001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份證校驗碼不正確 的本地化字符串。
        /// </summary>
        public static string _Code11001_104 {
            get {
                return ResourceManager.GetString("_Code11001_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轉換值出錯,不為數字 的本地化字符串。
        /// </summary>
        public static string _Code11001_105 {
            get {
                return ResourceManager.GetString("_Code11001_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在對應省份 的本地化字符串。
        /// </summary>
        public static string _Code11001_106 {
            get {
                return ResourceManager.GetString("_Code11001_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轉換日期值出錯 的本地化字符串。
        /// </summary>
        public static string _Code11001_107 {
            get {
                return ResourceManager.GetString("_Code11001_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出可转换的日期 的本地化字符串。
        /// </summary>
        public static string _Code11002_1 {
            get {
                return ResourceManager.GetString("_Code11002_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]不合法的農曆日期,年份不在可轉換範圍[{1}-{2}] 的本地化字符串。
        /// </summary>
        public static string _Code11002_101 {
            get {
                return ResourceManager.GetString("_Code11002_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]不合法的農曆日期,月份不存在。 的本地化字符串。
        /// </summary>
        public static string _Code11002_102 {
            get {
                return ResourceManager.GetString("_Code11002_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合法的農曆日期,[{0}日]不存在 的本地化字符串。
        /// </summary>
        public static string _Code11002_103 {
            get {
                return ResourceManager.GetString("_Code11002_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合法的農曆日期,[{0}月]不為闰月。 的本地化字符串。
        /// </summary>
        public static string _Code11002_104 {
            get {
                return ResourceManager.GetString("_Code11002_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]天數不為有效值[0-31] 的本地化字符串。
        /// </summary>
        public static string _Code11002_105 {
            get {
                return ResourceManager.GetString("_Code11002_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持類型轉換 的本地化字符串。
        /// </summary>
        public static string _Code11002_106 {
            get {
                return ResourceManager.GetString("_Code11002_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不為日期類型 的本地化字符串。
        /// </summary>
        public static string _Code11002_107 {
            get {
                return ResourceManager.GetString("_Code11002_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申請 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量 的本地化字符串。
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩 的本地化字符串。
        /// </summary>
        public static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权 的本地化字符串。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刪除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編輯 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能 的本地化字符串。
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件信息 的本地化字符串。
        /// </summary>
        public static string FileInfo {
            get {
                return ResourceManager.GetString("FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字 的本地化字符串。
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 記事本 的本地化字符串。
        /// </summary>
        public static string Notepad {
            get {
                return ResourceManager.GetString("Notepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 葡文 的本地化字符串。
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星级 的本地化字符串。
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始格式 的本地化字符串。
        /// </summary>
        public static string RawFormat {
            get {
                return ResourceManager.GetString("RawFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始格式編號 的本地化字符串。
        /// </summary>
        public static string RawFormatID {
            get {
                return ResourceManager.GetString("RawFormatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發送 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方案 的本地化字符串。
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測試 的本地化字符串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 檢視 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
