//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18063
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 證件號碼格式不符合 的當地語系化字串。
        /// </summary>
        internal static string _Code11001_1 {
            get {
                return ResourceManager.GetString("_Code11001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份證校驗碼不正確 的當地語系化字串。
        /// </summary>
        internal static string _Code11001_104 {
            get {
                return ResourceManager.GetString("_Code11001_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換值出錯,不為數字 的當地語系化字串。
        /// </summary>
        internal static string _Code11001_105 {
            get {
                return ResourceManager.GetString("_Code11001_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不存在對應省份 的當地語系化字串。
        /// </summary>
        internal static string _Code11001_106 {
            get {
                return ResourceManager.GetString("_Code11001_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換日期值出錯 的當地語系化字串。
        /// </summary>
        internal static string _Code11001_107 {
            get {
                return ResourceManager.GetString("_Code11001_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 超出可转换的日期 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_1 {
            get {
                return ResourceManager.GetString("_Code11002_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [{0}]不合法的農曆日期,年份不在可轉換範圍[{1}-{2}] 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_101 {
            get {
                return ResourceManager.GetString("_Code11002_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [{0}]不合法的農曆日期,月份不存在。 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_102 {
            get {
                return ResourceManager.GetString("_Code11002_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合法的農曆日期,[{0}日]不存在 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_103 {
            get {
                return ResourceManager.GetString("_Code11002_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合法的農曆日期,[{0}月]不為闰月。 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_104 {
            get {
                return ResourceManager.GetString("_Code11002_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [{0}]天數不為有效值[0-31] 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_105 {
            get {
                return ResourceManager.GetString("_Code11002_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不支持類型轉換 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_106 {
            get {
                return ResourceManager.GetString("_Code11002_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不為日期類型 的當地語系化字串。
        /// </summary>
        internal static string _Code11002_107 {
            get {
                return ResourceManager.GetString("_Code11002_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請 的當地語系化字串。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作者 的當地語系化字串。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批量 的當地語系化字串。
        /// </summary>
        internal static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中文 的當地語系化字串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 评论 的當地語系化字串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 压缩 的當地語系化字串。
        /// </summary>
        internal static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版权 的當地語系化字串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 描述 的當地語系化字串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文 的當地語系化字串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件信息 的當地語系化字串。
        /// </summary>
        internal static string FileInfo {
            get {
                return ResourceManager.GetString("FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 关键字 的當地語系化字串。
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 语言 的當地語系化字串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 記事本 的當地語系化字串。
        /// </summary>
        internal static string Notepad {
            get {
                return ResourceManager.GetString("Notepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 葡文 的當地語系化字串。
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星级 的當地語系化字串。
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原始格式 的當地語系化字串。
        /// </summary>
        internal static string RawFormat {
            get {
                return ResourceManager.GetString("RawFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原始格式編號 的當地語系化字串。
        /// </summary>
        internal static string RawFormatID {
            get {
                return ResourceManager.GetString("RawFormatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拒绝 的當地語系化字串。
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 保存 的當地語系化字串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發送 的當地語系化字串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 方案 的當地語系化字串。
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主题 的當地語系化字串。
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提交 的當地語系化字串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 測試 的當地語系化字串。
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 标题 的當地語系化字串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未知的 的當地語系化字串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版本 的當地語系化字串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢視 的當地語系化字串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
