//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 證件號碼格式不符合 的當地語系化字串。
        /// </summary>
        public static string Code11001_1 {
            get {
                return ResourceManager.GetString("Code11001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份證校驗碼不正確 的當地語系化字串。
        /// </summary>
        public static string Code11001_104 {
            get {
                return ResourceManager.GetString("Code11001_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換值出錯,不為數字 的當地語系化字串。
        /// </summary>
        public static string Code11001_105 {
            get {
                return ResourceManager.GetString("Code11001_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不存在對應省份 的當地語系化字串。
        /// </summary>
        public static string Code11001_106 {
            get {
                return ResourceManager.GetString("Code11001_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換日期值出錯 的當地語系化字串。
        /// </summary>
        public static string Code11001_107 {
            get {
                return ResourceManager.GetString("Code11001_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 超出可转换的日期 的當地語系化字串。
        /// </summary>
        public static string Code11002_1 {
            get {
                return ResourceManager.GetString("Code11002_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [{0}]不合法的農曆日期,年份不在可轉換範圍[{1}-{2}] 的當地語系化字串。
        /// </summary>
        public static string Code11002_101 {
            get {
                return ResourceManager.GetString("Code11002_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [{0}]不合法的農曆日期,月份不存在。 的當地語系化字串。
        /// </summary>
        public static string Code11002_102 {
            get {
                return ResourceManager.GetString("Code11002_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合法的農曆日期,[{0}]日不存在 的當地語系化字串。
        /// </summary>
        public static string Code11002_103 {
            get {
                return ResourceManager.GetString("Code11002_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合法的農曆日期,[{0}]月不為闰月。 的當地語系化字串。
        /// </summary>
        public static string Code11002_104 {
            get {
                return ResourceManager.GetString("Code11002_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [{0}]天數不為有效值[0-31] 的當地語系化字串。
        /// </summary>
        public static string Code11002_105 {
            get {
                return ResourceManager.GetString("Code11002_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不支持類型格式化輸了 的當地語系化字串。
        /// </summary>
        public static string Code11002_106 {
            get {
                return ResourceManager.GetString("Code11002_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不為日期類型 的當地語系化字串。
        /// </summary>
        public static string Code11002_107 {
            get {
                return ResourceManager.GetString("Code11002_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test 的當地語系化字串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
