//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Draw {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DrawResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DrawResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Draw.DrawResource", typeof(DrawResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 所有Exifs 的當地語系化字串。
        /// </summary>
        internal static string AllExifs {
            get {
                return ResourceManager.GetString("AllExifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 色度表 的當地語系化字串。
        /// </summary>
        internal static string ChrominanceTable {
            get {
                return ResourceManager.GetString("ChrominanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 比对 的當地語系化字串。
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立時間 的當地語系化字串。
        /// </summary>
        internal static string DateTimeDigitized {
            get {
                return ResourceManager.GetString("DateTimeDigitized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拍攝時間 的當地語系化字串。
        /// </summary>
        internal static string DateTimeOriginal {
            get {
                return ResourceManager.GetString("DateTimeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 设备信息 的當地語系化字串。
        /// </summary>
        internal static string EquipmentInfo {
            get {
                return ResourceManager.GetString("EquipmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 设备廠商 的當地語系化字串。
        /// </summary>
        internal static string EquipmentMake {
            get {
                return ResourceManager.GetString("EquipmentMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 设备型号 的當地語系化字串。
        /// </summary>
        internal static string EquipmentModel {
            get {
                return ResourceManager.GetString("EquipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exif版本 的當地語系化字串。
        /// </summary>
        internal static string ExifVersion {
            get {
                return ResourceManager.GetString("ExifVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 曝光方式 的當地語系化字串。
        /// </summary>
        internal static string ExposureProgram {
            get {
                return ResourceManager.GetString("ExposureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 曝光时间 的當地語系化字串。
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 闪光灯模式 的當地語系化字串。
        /// </summary>
        internal static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 35mm胶卷 的當地語系化字串。
        /// </summary>
        internal static string FocalLengthIn35mmFilm {
            get {
                return ResourceManager.GetString("FocalLengthIn35mmFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地理信息 的當地語系化字串。
        /// </summary>
        internal static string GeoInfo {
            get {
                return ResourceManager.GetString("GeoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS 的當地語系化字串。
        /// </summary>
        internal static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖像信息 的當地語系化字串。
        /// </summary>
        internal static string ImageInfo {
            get {
                return ResourceManager.GetString("ImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ISO光圈 的當地語系化字串。
        /// </summary>
        internal static string ISOSpeedRatings {
            get {
                return ResourceManager.GetString("ISOSpeedRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 光源 的當地語系化字串。
        /// </summary>
        internal static string LightSource {
            get {
                return ResourceManager.GetString("LightSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 亮度表 的當地語系化字串。
        /// </summary>
        internal static string LuminanceTable {
            get {
                return ResourceManager.GetString("LuminanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 测光模式 的當地語系化字串。
        /// </summary>
        internal static string MeteringMode {
            get {
                return ResourceManager.GetString("MeteringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 像素 的當地語系化字串。
        /// </summary>
        internal static string Pix {
            get {
                return ResourceManager.GetString("Pix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解析度 的當地語系化字串。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分辨率单元 的當地語系化字串。
        /// </summary>
        internal static string ResolutionUnit {
            get {
                return ResourceManager.GetString("ResolutionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 饱和 的當地語系化字串。
        /// </summary>
        internal static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清晰度 的當地語系化字串。
        /// </summary>
        internal static string Sharpness {
            get {
                return ResourceManager.GetString("Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 快门速度 的當地語系化字串。
        /// </summary>
        internal static string ShutterSpeed {
            get {
                return ResourceManager.GetString("ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 縮略圖 的當地語系化字串。
        /// </summary>
        internal static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 白平衡 的當地語系化字串。
        /// </summary>
        internal static string WhiteBalance {
            get {
                return ResourceManager.GetString("WhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 YCbCr定位 的當地語系化字串。
        /// </summary>
        internal static string YCbCrPositioning {
            get {
                return ResourceManager.GetString("YCbCrPositioning", resourceCulture);
            }
        }
    }
}
