//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Draw {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DrawResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DrawResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Draw.DrawResource", typeof(DrawResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有Exifs 的本地化字符串。
        /// </summary>
        internal static string AllExifs {
            get {
                return ResourceManager.GetString("AllExifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色度表 的本地化字符串。
        /// </summary>
        internal static string ChrominanceTable {
            get {
                return ResourceManager.GetString("ChrominanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比对 的本地化字符串。
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立時間 的本地化字符串。
        /// </summary>
        internal static string DateTimeDigitized {
            get {
                return ResourceManager.GetString("DateTimeDigitized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍攝時間 的本地化字符串。
        /// </summary>
        internal static string DateTimeOriginal {
            get {
                return ResourceManager.GetString("DateTimeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备信息 的本地化字符串。
        /// </summary>
        internal static string EquipmentInfo {
            get {
                return ResourceManager.GetString("EquipmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备廠商 的本地化字符串。
        /// </summary>
        internal static string EquipmentMake {
            get {
                return ResourceManager.GetString("EquipmentMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备型号 的本地化字符串。
        /// </summary>
        internal static string EquipmentModel {
            get {
                return ResourceManager.GetString("EquipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exif版本 的本地化字符串。
        /// </summary>
        internal static string ExifVersion {
            get {
                return ResourceManager.GetString("ExifVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光方式 的本地化字符串。
        /// </summary>
        internal static string ExposureProgram {
            get {
                return ResourceManager.GetString("ExposureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间 的本地化字符串。
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闪光灯模式 的本地化字符串。
        /// </summary>
        internal static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無閃光燈 的本地化字符串。
        /// </summary>
        internal static string Flash_Name0 {
            get {
                return ResourceManager.GetString("Flash_Name0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈 的本地化字符串。
        /// </summary>
        internal static string Flash_Name1 {
            get {
                return ResourceManager.GetString("Flash_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,强制,無回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name13 {
            get {
                return ResourceManager.GetString("Flash_Name13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,强制,回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name15 {
            get {
                return ResourceManager.GetString("Flash_Name15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無光灯,强制 的本地化字符串。
        /// </summary>
        internal static string Flash_Name16 {
            get {
                return ResourceManager.GetString("Flash_Name16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無光灯,自动 的本地化字符串。
        /// </summary>
        internal static string Flash_Name24 {
            get {
                return ResourceManager.GetString("Flash_Name24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,自动 的本地化字符串。
        /// </summary>
        internal static string Flash_Name25 {
            get {
                return ResourceManager.GetString("Flash_Name25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,自动,無回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name29 {
            get {
                return ResourceManager.GetString("Flash_Name29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,自动,回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name31 {
            get {
                return ResourceManager.GetString("Flash_Name31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無閃光燈功能 的本地化字符串。
        /// </summary>
        internal static string Flash_Name32 {
            get {
                return ResourceManager.GetString("Flash_Name32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,無回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name5 {
            get {
                return ResourceManager.GetString("Flash_Name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,紅眼 的本地化字符串。
        /// </summary>
        internal static string Flash_Name65 {
            get {
                return ResourceManager.GetString("Flash_Name65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,紅眼,無回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name69 {
            get {
                return ResourceManager.GetString("Flash_Name69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name7 {
            get {
                return ResourceManager.GetString("Flash_Name7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,紅眼,回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name71 {
            get {
                return ResourceManager.GetString("Flash_Name71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,强制,紅眼 的本地化字符串。
        /// </summary>
        internal static string Flash_Name73 {
            get {
                return ResourceManager.GetString("Flash_Name73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,强制,紅眼,無回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name77 {
            get {
                return ResourceManager.GetString("Flash_Name77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,强制,紅眼,回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name79 {
            get {
                return ResourceManager.GetString("Flash_Name79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,自动,紅眼 的本地化字符串。
        /// </summary>
        internal static string Flash_Name83 {
            get {
                return ResourceManager.GetString("Flash_Name83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,强制 的本地化字符串。
        /// </summary>
        internal static string Flash_Name9 {
            get {
                return ResourceManager.GetString("Flash_Name9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,自动,紅眼,無回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name93 {
            get {
                return ResourceManager.GetString("Flash_Name93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光燈,自动,紅眼,回應閃光 的本地化字符串。
        /// </summary>
        internal static string Flash_Name95 {
            get {
                return ResourceManager.GetString("Flash_Name95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 35mm胶卷 的本地化字符串。
        /// </summary>
        internal static string FocalLengthIn35mmFilm {
            get {
                return ResourceManager.GetString("FocalLengthIn35mmFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地理信息 的本地化字符串。
        /// </summary>
        internal static string GeoInfo {
            get {
                return ResourceManager.GetString("GeoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS 的本地化字符串。
        /// </summary>
        internal static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圖像信息 的本地化字符串。
        /// </summary>
        internal static string ImageInfo {
            get {
                return ResourceManager.GetString("ImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO光圈 的本地化字符串。
        /// </summary>
        internal static string ISOSpeedRatings {
            get {
                return ResourceManager.GetString("ISOSpeedRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源 的本地化字符串。
        /// </summary>
        internal static string LightSource {
            get {
                return ResourceManager.GetString("LightSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D55 的本地化字符串。
        /// </summary>
        internal static string LightSource_D55 {
            get {
                return ResourceManager.GetString("LightSource_D55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D65 的本地化字符串。
        /// </summary>
        internal static string LightSource_D65 {
            get {
                return ResourceManager.GetString("LightSource_D65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D75 的本地化字符串。
        /// </summary>
        internal static string LightSource_D75 {
            get {
                return ResourceManager.GetString("LightSource_D75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日光 的本地化字符串。
        /// </summary>
        internal static string LightSource_Daylight {
            get {
                return ResourceManager.GetString("LightSource_Daylight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 閃光 的本地化字符串。
        /// </summary>
        internal static string LightSource_Flash {
            get {
                return ResourceManager.GetString("LightSource_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 螢光燈 的本地化字符串。
        /// </summary>
        internal static string LightSource_Fluorescent {
            get {
                return ResourceManager.GetString("LightSource_Fluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 標準照度A 的本地化字符串。
        /// </summary>
        internal static string LightSource_StandardLightA {
            get {
                return ResourceManager.GetString("LightSource_StandardLightA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 標準照度B 的本地化字符串。
        /// </summary>
        internal static string LightSource_StandardLightB {
            get {
                return ResourceManager.GetString("LightSource_StandardLightB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 標準照度C 的本地化字符串。
        /// </summary>
        internal static string LightSource_StandardLightC {
            get {
                return ResourceManager.GetString("LightSource_StandardLightC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鵝絲類 的本地化字符串。
        /// </summary>
        internal static string LightSource_Tungsten {
            get {
                return ResourceManager.GetString("LightSource_Tungsten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度表 的本地化字符串。
        /// </summary>
        internal static string LuminanceTable {
            get {
                return ResourceManager.GetString("LuminanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中央偏重平均測光 的本地化字符串。
        /// </summary>
        internal static string Metering_CenterWeightedAverage {
            get {
                return ResourceManager.GetString("Metering_CenterWeightedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均測光 的本地化字符串。
        /// </summary>
        internal static string Metering_ModeAverage {
            get {
                return ResourceManager.GetString("Metering_ModeAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分區測光 的本地化字符串。
        /// </summary>
        internal static string Metering_MultiSegment {
            get {
                return ResourceManager.GetString("Metering_MultiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多点測光 的本地化字符串。
        /// </summary>
        internal static string Metering_MultiSpot {
            get {
                return ResourceManager.GetString("Metering_MultiSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 局部測光 的本地化字符串。
        /// </summary>
        internal static string Metering_Partial {
            get {
                return ResourceManager.GetString("Metering_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測光 的本地化字符串。
        /// </summary>
        internal static string Metering_Spot {
            get {
                return ResourceManager.GetString("Metering_Spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测光模式 的本地化字符串。
        /// </summary>
        internal static string MeteringMode {
            get {
                return ResourceManager.GetString("MeteringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        internal static string Pix {
            get {
                return ResourceManager.GetString("Pix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string RawFormat {
            get {
                return ResourceManager.GetString("RawFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析度 的本地化字符串。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率单元 的本地化字符串。
        /// </summary>
        internal static string ResolutionUnit {
            get {
                return ResourceManager.GetString("ResolutionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 饱和 的本地化字符串。
        /// </summary>
        internal static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清晰度 的本地化字符串。
        /// </summary>
        internal static string Sharpness {
            get {
                return ResourceManager.GetString("Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快门速度 的本地化字符串。
        /// </summary>
        internal static string ShutterSpeed {
            get {
                return ResourceManager.GetString("ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 縮略圖 的本地化字符串。
        /// </summary>
        internal static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白平衡 的本地化字符串。
        /// </summary>
        internal static string WhiteBalance {
            get {
                return ResourceManager.GetString("WhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YCbCr定位 的本地化字符串。
        /// </summary>
        internal static string YCbCrPositioning {
            get {
                return ResourceManager.GetString("YCbCrPositioning", resourceCulture);
            }
        }
    }
}
